---
# Source: traefik/templates/rbac.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefikv1
---
# Source: traefik/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefikv1
  labels:
    app: traefik
    chart: traefik-1.87.7
    release: "traefikv1"
    heritage: "Helm"
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
      [entryPoints.traefik]
      address = ":8080"
    [ping]
    entryPoint = "http"
    [kubernetes]
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
---
# Source: traefik/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefikv1
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
---
# Source: traefik/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefikv1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefikv1
subjects:
- kind: ServiceAccount
  name: traefikv1
  namespace: traefikv1
---
# Source: traefik/templates/dashboard-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefikv1-dashboard
  labels:
    app: traefik
    chart: traefik-1.87.7
    release: "traefikv1"
    heritage: "Helm"
  annotations:
spec:
  type: ClusterIP
  selector:
    app: traefik
    release: traefikv1
  ports:
  - name: dashboard-http
    port: 80
    targetPort: 8080
---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefikv1
  labels:
    app: traefik
    chart: traefik-1.87.7
    release: "traefikv1"
    heritage: "Helm"
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: traefik
    release: traefikv1
  ports:
  - port: 443
    name: https
    targetPort: httpn
  - port: 80
    name: http
    targetPort: http
---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefikv1
  labels:
    app: traefik
    chart: traefik-1.87.7
    release: "traefikv1"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefikv1
  template:
    metadata:
      annotations:
        checksum/config: a89fefc72e86abc57e8c9d6f4995bbc32c7a26052b02feadc2ae4570533e3e80
      labels:
        app: traefik
        chart: traefik-1.87.7
        release: "traefikv1"
        heritage: "Helm"
    spec:
      serviceAccountName: traefikv1
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.26
        imagePullPolicy: IfNotPresent
        name: traefikv1
        resources:
          {}
        readinessProbe:
          httpGet:
            path: /ping
            port: "http"
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: "http"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: httpn
          containerPort: 8880
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: dash
          containerPort: 8080
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml

      volumes:
      - name: config
        configMap:
          name: traefikv1

---
# Source: traefik/templates/dashboard-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefikv1-dashboard
  labels:
    app: traefik
    chart: traefik-1.87.7
    release: "traefikv1"
    heritage: "Helm"
  annotations:
spec:
  rules:
  - host: traefik.example.com
    http:
      paths:
      - backend:
          serviceName: traefikv1-dashboard
          servicePort: dashboard-http
